# Generated by Django 2.0.6 on 2018-06-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('duration', models.DurationField()),
                ('year', models.PositiveSmallIntegerField()),
                ('course', models.ForeignKey(on_delete=None, to='course.Course')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('max_marks', models.PositiveSmallIntegerField()),
                ('question_order', models.PositiveSmallIntegerField()),
                ('marking_scheme', models.TextField()),
                ('assessment', models.ForeignKey(on_delete=None, to='assessment.Assessment')),
                ('outcome', models.ForeignKey(on_delete=None, to='course.CourseOutcome')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtained_marks', models.PositiveSmallIntegerField()),
                ('remarks', models.TextField()),
                ('question', models.ForeignKey(on_delete=None, to='assessment.AssessmentQuestion')),
                ('student', models.ForeignKey(on_delete=None, to='user.User')),
            ],
        ),
    ]
