# Generated by Django 2.0.6 on 2018-06-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_join', models.DateField()),
                ('date_of_leave', models.DateField()),
                ('qualification', models.CharField(max_length=50)),
                ('specialization', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('department', models.ForeignKey(on_delete=None, to='department.Department')),
                ('user', models.ForeignKey(on_delete=None, to='user.User')),
            ],
        ),
    ]
