# Generated by Django 2.0.7 on 2018-10-26 17:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('added_by', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=2000)),
                ('duration', models.DurationField()),
                ('funding_agency', models.CharField(max_length=100)),
                ('amount', models.BigIntegerField()),
                ('date_of_start', models.DateField()),
                ('status', models.CharField(choices=[('Completed', 'COMPLETED'), ('OnGoing', 'ON GOING'), ('Restricted', 'RESTRICTED')], max_length=50)),
                ('remarks', models.TextField()),
                ('type', models.CharField(choices=[('RS', 'RESEARCH SPONSORED'), ('CSY', 'CONSULTANCY'), ('IDEA', 'IDEA'), ('MNR', 'MENTORED'), ('ACA_V', 'ACADEMIC VOLUNTARY'), ('ACA_A', 'ACADEMIC ALLOTTED'), ('SMR', 'SEMINAR')], max_length=30)),
                ('resources', models.CharField(max_length=1000)),
                ('max_number_ProjectMembers', models.IntegerField()),
                ('featured', models.BooleanField(default=False)),
                ('report', models.BooleanField(default=False)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=None, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_view_project_list', 'can view project list'), ('can_mentor_project', 'can mentor project'), ('can_report_project', 'can report project'), ('can_allot_projects', 'can allot project'), ('can_verify_projects', 'can verify project'), ('can_view_self_project', 'can view self project')),
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(max_length=10, unique=True)),
                ('team_name', models.CharField(max_length=500, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=None, to='project.Project')),
                ('team_leader', models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_view_team', 'can view team'),),
            },
        ),
        migrations.AddField(
            model_name='projectmember',
            name='team_id',
            field=models.ForeignKey(on_delete=None, to='project.Team'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='user',
            field=models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='projectmember',
            unique_together={('user', 'team_id')},
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('added_by', 'title', 'supervisor')},
        ),
    ]
