# Generated by Django 2.0.6 on 2018-06-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('User_id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('Password', models.CharField(max_length=16)),
                ('Name', models.CharField(max_length=50)),
                ('Date_of_birth', models.DateField()),
                ('Sex', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=20)),
                ('Contact', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Photo', models.ImageField(upload_to='')),
                ('Category', models.CharField(max_length=10)),
                ('Blood_group', models.CharField(max_length=3, null=True)),
            ],
        ),
    ]
