# Generated by Django 2.0.6 on 2018-06-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('user_name', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=10)),
                ('contact', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
